freedomofpress/securethenews

devops/Makefile, devops/molecule.yml, devops/playbook.yml, devops/requirements.yml, securethenews/requirements.txt
I saw some weird issues locally when trying to run from scratch that I wasnt able to reproduce in prod. In particular I needed to add in the following to my local roles copy:
```yaml
- name: Upgrade PIP
pip:
name: "{{ item }}"
virtualenv_python: "{{ django_stack_venv_python }}"
executable: "{{ django_stack_gcorn_home }}/{{ django_stack_app_name }}/bin/pip"
virtualenv_site_packages: "{{ django_stack_venv_sitepackage }}"
extra_args: --upgrade
with_items:
- pip
- setuptools
```
Should I add this upstream to `django_stack` ? im not really certain if theres any negative consequence to always updating pip + setuptools to the latest in prod, so I'm not sold on this without more testing. Id rather spend that testing time trying to implement pip deps into debian pkgs - but ill be willing to …
=> Infra 318 django bump

README.md, news_sites.csv, securethenews/api/apps.py, securethenews/api/filters.py, securethenews/api/serializers.py, securethenews/api/tests.py, securethenews/api/urls.py, securethenews/api/views.py, securethenews/requirements.txt, securethenews/securethenews/settings/base.py, securethenews/securethenews/templates/rest_framework/api.html, securethenews/securethenews/urls.py
This uses the Django REST framework, which adds a nice browsable API
as well.
API can be found at /api/v1, /api redirects to it.
=> Add read-only REST API for site/scan data; enable CORS for GET/HEAD

securethenews/blog/models.py, securethenews/blog/tests.py
Fixes #97 by ordering blog posts on the index page by the primary key column `id` instead of the `date` column as suggested by @garrettr in the issue description. 
Adds a unit test to verify this behavior and prevent future regressions.
=> Fix blog ordering on blog index page

news_sites.csv
NPR.com is a redirect to NPR.org.
=> Corrected the site domain for NPR.

molecule/ci/playbook.yml, molecule/ci/requirements.yml, molecule/ci/tests/test_logging.py, molecule/requirements.txt, molecule/shared_tests/test_pshtt.py
Everyone said, why the hell are you shipping around virtualenv's that doesnt sound like a great idea .... Hah. Yep - that was good advice :| Anywhoo. This PR applies a fix for that situation that addresses deployments to debian jessie. Thanks to the Power Of the Django Ansible Role :tm:, this logic is extensible and relevant fixes can be made for other environments.
TL;DR - When building a virtualenv for deloyment, the build environnment needs to match the target environment.
=> INFRA-529 Address broken virtualenv delivery logic

news_sites.csv
We received a request via the general FPF contact form requesting the
change. There was a slight delay in making the change on the live site
(see #130 for details), but it's live now. A change to the underlying
CSV is required to stay in sync, and to prevent regressions in the prod
database.
Closes #127.
=> Updates domain name for EL PAÍS website

molecule/dev/playbook.yml
- When the grsec kernel is not present, the previous logic caused
a default Node image (without the custom CI Dockerfile) to be
used. As a result, `npm install` would fail (due to missing
`python` and `g++` dependencies) and `make dev-go` would time
out at this stage.
- The SHA-256 hash was not appended to the name of the Django
image. Once the bug above was fixed, this caused Docker to
look for an image called `stn_django:latest` (`latest` is the
default tag). Since that image does not exist, it would fail
at this stage.
=> Fix bugs in Ansible playbook that caused `make dev-go` to fail

molecule/requirements.in, molecule/requirements.txt, requirements.in, requirements.txt
Bumps the `markdown2` dependency to satisfy the `make safety` check, by upgrading to a patched version. Also upgraded Ansible for a similar reason (bad `pycrypto` dependency), and finally bumped Django to 1.11.11 for the latest security fixes listed in https://www.djangoproject.com/weblog/2018/mar/06/security-releases/
Closes #153.
=> Patches pip dependencies (Django, markdown2, Ansible)

.circleci/config.yml, Makefile, molecule/requirements.in, molecule/requirements.txt, requirements.in
**Depends on #149, review and merge that first.**
Adds static analysis via [bandit](https://github.com/openstack/bandit), as suggested by @emkll. Already wired up CI.
=> Static analysis via bandit

.circleci/config.yml, securethenews/requirements.in, securethenews/requirements.txt
- Add CI workflow for securethenews
- Add safety_check job that is run nightly and for each CI run
- Update bandit and safety each time the makefile target is called
=> Upgrade safety and bandit for each run and regular safety checks in CI

Makefile, docker-compose.yaml
This ensures that containers are not exposed or reachable to other hosts
on local networks or VPN.
How to test: 
* Ensure securethenews is not impacted by CVE-2018-10903
* CI should pass
* Checkout master
* make dev
* open browser to `<IP_OF_HOST>:8000`
* observe web page
* checkout this branch
* make dev
* open browser to `<IP_OF_HOST>:8000`
* do not observe web page
=> Bind Docker ports to localhost only

Makefile
=> Ignore pyopenssl and requests

Makefile, securethenews/requirements.in, securethenews/requirements.txt
Due to CVE-2019-3498 (see https://www.djangoproject.com/weblog/2019/jan/04/security-releases/)
=> Upgrade to Django 1.11.18

securethenews/requirements.in, securethenews/requirements.txt
Fixes CVE-2019-6975 and packaging error introduced in 1.1.19, see:
* https://docs.djangoproject.com/en/dev/releases/1.11.19/
* https://docs.djangoproject.com/en/dev/releases/1.11.20/
=> Update Django to 1.11.20

.gitignore, ci-docker-compose.yaml, docker-compose.yaml, docker/1-prod-node, docker/DevDjangoDockerfile, docker/ProdDjangoDockerfile, package-lock.json, package.json
Bumps the nodejs version to a supported LTS. The actual deploy logic must be updated separately—first, let's validate no breakage to the best of our ability here.
For the most part, I've abstained from updating the node dependencies themselves, opting to bump only the parent nodejs/npm versions. The exception is to the `jade` dep; see commit messages for details there. 
First, it's critical that you run `docker-compose build` (or `docker-compose up --build`) on this branch. otherwise, you'll still be using the _old_ containers, even if you have this branch checked out! See output from docker-compose for reference:
> WARNING: Image for service node was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Fire up …
=> Upgrades Node version 6.11.0 -> 10.15.1

Pipfile, Pipfile.lock, pledges/forms.py
This pull request upgrades our testinfra version as well as other dependencies in `Pipfile.lock`.
These changes were accomplished with the command `pipenv lock`.
The motivation for this change is that the testinfra hash changed upstream, so pipenv install was failing.
=> Upgrade testinfra

pledges/views.py, securethenews/requirements.in, securethenews/requirements.txt, securethenews/settings/base.py, securethenews/urls.py
This pull request:
1. Changes our Django requirement from 1.1.x to 2.0.x
2. Updates url definitions to be compatible with Django 2.0
3. Updates our middleware to be compatible with Django 2.0
4. Updates `django-crispy-forms` to be compatible with Django 2.0
Refs freedomofpress/fpf-www-projects#21
=> Upgrade to Django 2.0.x

Makefile, api/filters.py, ci-docker-compose.yaml, docker-compose.yaml, securethenews/requirements.in, securethenews/requirements.txt
This pull request:
1. Changes the makefile to ensure that the `update-pip-dependencies` command runs under python 3.6
2. Upgrades our database container to postgresql 9.5
3. Updates Django to version 2.1.7 (the latest version as of now), and updates `django-filter` to the latest version to maintain compatibility.
Refs freedomofpress/fpf-www-projects#21
=> Upgrade to Django 2.1

securethenews/requirements.in, securethenews/requirements.txt
We were pinning 2.2 because that worked well enough under Django 1.x.
Under 2.1, however, the analytics integration throws an error on a bool
type conversion. We saw the same error with the Django upgrade on another
website, and updating analytical to 2.5 resolved it, so doing the same here.
=> Bumps django-analytical 2.2 -> 2.5

securethenews/settings/production-debug.py
This change adds a settings file for secured production-like
environments that require manual debugging.  All it does is replicate
every other setting from production.py an then switch DEBUG to
true.  This is intended to be used during the sandbox testing.
=> Add settings for production-like environments that need debugging

.circleci/config.yml, Makefile
This pull request adds a make command to check for ungenerated migrations. I've also put the command into the CI config so it's run when building the site, so that we don't inadvertently merge any PRs without having included all necessary migrations.
=> Add make command to check for ungenerated migrations

Makefile, README.md, docker-compose.yaml, docker/DevDjangoDockerfile, docker/dev-django, securethenews/dev-requirements.in, securethenews/dev-requirements.txt
This pull request 
1. Adds the idea of development dependencies to this project, mostly copying how we do it elsewhere in our web sphere (e.g. see [Press Freedom Tracker](https://github.com/freedomofpress/tracker)).
2. Updates the docker compose settings to permit attaching such that you can interactively run the python debugger on our Django containers. I've also added some documentation for how to do this.
Refs freedomofpress/fpf-www-projects#39
=> Enable PDB and development requirements

.dockerignore, .gitignore, docker/DevDjangoDockerfile, docker/ProdDjangoDockerfile, docker/django-start.sh, home/views.py, home/wagtail_hooks.py, scripts/version-file.sh, securethenews/dev-requirements.txt, securethenews/requirements.in, securethenews/requirements.txt
This pull request adds a view to the admin area that, essentially, reads from a file and displays those file contents to the admin. In theory, this file is filled with information about the current git commit/branch that's deployed, something like
```
git log HEAD --oneline --no-walk
```
=> Add "gitinfo" view

securethenews/dev-requirements.txt, securethenews/requirements.in, securethenews/requirements.txt
This upgrade fixes a few security vulnerabilities.  
This change was generated by modifying `requirements.in` to require the version we want to upgrade to and running `make update-pip-dependencies`.
Refs freedomofpress/fpf-www-projects#58
=> Upgrade django to 2.1.10

securethenews/dev-requirements.txt, securethenews/requirements.in, securethenews/requirements.txt
This upgrade fixes a few security vulnerabilities.  See https://docs.djangoproject.com/en/2.1/releases/2.1.11/ for more information.
This change was generated by modifying requirements.in to require the version we want to upgrade to and running `make update-pip-dependencies`.
Refs freedomofpress/fpf-www-projects#68
=> Upgrade django 2.1.10 to 2.1.11

securethenews/dev-requirements.txt, securethenews/requirements.in, securethenews/requirements.txt, securethenews/settings/production.py
Two changes here, both intended to standardize the production logging story:
* Bumps logging reqs to include changes from https://github.com/freedomofpress/django-logging/pull/5
* Forces JSON logging format by disabling "other" loggers (which may not be logging in JSON)
Upon merge, the new container will be pushed to the testing cluster, and we can evaluate the logging change there.
Using the prod docker-compose environment, you can observe that on current master, each request generates at least two events, on JSON and one plaintext:
> django_1      | [2019-08-12 16:26:10 +0000] [21] [DEBUG] GET /sites/
django_1      | {"created": 1565627171, "levelname": "INFO", "request": {"data": {}, "meta": {"http_host": "localhost:8000", "http_user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) …
=> Forces JSON log format in prod settings

.github/CODEOWNERS
Per internal discussion, Cameron is a highly trusted contributor, and this will increase velocity and give us more consistent coverage for reviews.
=> Add Cameron Higby as trusted codeowner

Makefile, README.md
This pull request changes removes the makefile-based interface to the `createdevdata` command and updates the readme to instruct developers to invoke the command with `docker-compose` directly. This change brings this project into line with our other websites.
Refs freedomofpress/fpf-www-projects#38
=> Make createdevdata UI consistent with other projects

.circleci/config.yml
Fixes #206 
Renamed `safety_check_linters` to `safety_check`
=> Fixes nightly build of securethenews

client/src/styles/_social.scss, securethenews/templates/shared/social.html
Both Facebook and Twitter share endpoints expect that URLs are
URL-encoded; Facebook gracefully redirects, while Twitter ignores
URLs that are not URL-encoded.
Resolves #208
=> Remove Google Plus, fix Twitter share links

docker-compose.yaml, docker/NodeDockerfile, docker/ProdDjangoDockerfile, package-lock.json, prod-docker-compose.yaml
* In the process I've also extended our NodeDockerfile to allow
us to easily specify an NPM version as part of the
docker-compose file
* Since we are still on a supported LTS track with Node 10.x, I
decided to conservatively upgrade to the latest version of Node
10.x rather than upgrade to the absolutely latest Node (or even
the latest LTS track, which is node 12.x)
* I also updated our NodeDockerfile to use CMD rather than
ENTRYPOINT to run webpack. This is more consistent with how
those declarations are intended:
- Typically entrypoints accept a command and run some
environment logic before passing the command along
- This allows the command to be overridden by e.g. `docker run <cmd>`
* Among other things, this patches this vulnerability in npm …
=> Upgrade to latest version of npm and supported version of node

scripts/version-file.sh
Specifically, adds info on:
1. git tag (if HEAD is tagged; otherwise "N/A")
2. git branch (usually "master", but can be feature branches on
e.g. staging)
Hopefully this'll be more immediately useful than a simple list of the
commits, as we have now. The list of commits is preserved in these
changes.
Refs https://github.com/freedomofpress/infrastructure/issues/2305
Implementation ported from https://github.com/freedomofpress/securedrop.org/pull/663
If you want to review locally, run `docker-compose up --build`, then navigate to http://localhost:8000/admin/version/ . Examples of the before/after formatting can be found in https://github.com/freedomofpress/securedrop.org/pull/663
=> Expands git info on version endpoint

securethenews/dev-requirements.txt, securethenews/requirements.in, securethenews/requirements.txt
Refs https://github.com/freedomofpress/fpf-www-projects/issues/81
=> Upgrade to django 2.2.10 to fix CVE

Pipfile.lock, package-lock.json
CI currently fails on `npm audit`. I'd like to do some testing of the branch->CI->k8s flow, so master failing here makes things complicated.
I originally wanted to try updating the Python version as well as packages, which is why the pip lock commit comes first, but punting on that for now.
=> Update pip and npm

home/templates/home/home_page.html
The limit was intended for larger taxonomies and hides key regions
from the homepage.
Reported in #212
=> Increase regions displayed above the fold to 7

package-lock.json, package.json
This pull request upgrades to the latest version of `minimist` everywhere I could find, mostly done with `npm audit fix` though I did have to manually upgrade `webpack` and `watchify`'s dependencies. Not sure why this was less automated than in the past, but it seemed to clear up the errors on my machine, at least.
=> Fix npm audit failures

securethenews/dev-requirements.txt, securethenews/requirements.in, securethenews/requirements.txt
Fixes vulnerabilities noted by the `safety` check.
Packages affected:
* django-cors-headers: 2.1.0 to 3.2.1 (no breaking changes)
* django: 2.2.10 to 2.2.12
* pillow: 4.2.1 to 6.2.2
* requests: 2.18.4 to 2.23.0 (no vulnerability, required for urllib3 upgrade)
* urllib3: 1.22 to 1.25.8
=> Upgrade packages with security vulnerabilities

securethenews/dev-requirements.txt, securethenews/requirements.in, securethenews/requirements.txt
Updates to wagtail 2.7.2 to fix CVE-2020-11001 - prevent XSS attack via page revision comparison view (Vlad Gerasimenko, Matt Westcott) https://github.com/wagtail/wagtail/releases/tag/v2.7.2
=> Updates wagtail to 2.7.2 to fix CVEs

docker/DevDjangoDockerfile, docker/ProdDjangoDockerfile, docker/django-start.sh
The container image should report its process as `gunicorn` in prod
contexts, so that the application gracefully terminates when it receives
a SIGTERM from the managing process [0]. Without using `exec`, the container
reports that sh is the active process (sh -> bash -> gunicorn), so a
SIGTERM to sh results in SIGKILL on the children.
[0] https://docs.gunicorn.org/en/stable/signals.html
=> Uses exec in container entrypoint

securethenews/settings/production.py
This tweaks a couple things I ran into running STN in GKE:
- Allow for not setting the project ID (will default to the GKE cluster's project, which is what we want)
- Warn if credentials are unset (there are a couple ways you can do this, and the failure modes are rather inscrutable to debug otherwise)
- Send logs to stdout. In GKE, you just do the standard k8s thing of printing logs to stdout/stderr. However, logs on stderr are considered "errors" regardless of the application-level severity in the JSON payload. It looks like:
I investigated the [checks framework](https://docs.djangoproject.com/en/3.0/topics/checks/) at @harrislapiroff's suggestion but since it normally doesn't run in `production` and seems more suited for static checks I thought it would be better to just use `logging` …
=> Settings improvements: GS env vars, logging

Makefile
This pull request adds `-e` to the `make` command's `bash` call used to execute the test suite.
`bash -e` ensures that non-zero exit codes during any "intermediate"
command (e.g. in a sequence of semicolon separated commands, which we
have here) are propagated upwards and the entire call to `bash`
returns a non-zero code.  This is needed so that Circle CI becomes
aware that the test command failed.
It's possible to see the effect of this in action locally but running the test suite where you know it will fail then inspecting the exit status with `echo $?`.
If you modify a test so it will fail, e.g. with an `assert False` statement, then run 
```
make app-tests-dev
```
The exit code _with_ this change should be nonzero. Without this change, on master, should be zero.
=> Ensure CI test job fails when tests fail

Makefile, package-lock.json, securethenews/dev-requirements.txt, securethenews/requirements.txt
This pull request updates Django to 2.2.14 to fix some security vulnerabilities and also instructs safety to ignore several vulnerabilities in the Pillow library until the wagtail LTS branch relaxes its dependency on the pillow 6.2.x branch, which is no longer supported. 
I also updated the `rsa` package to the latest version, fixing a vulnerability documented at [CVE-2020-13757](https://nvd.nist.gov/vuln/detail/CVE-2020-13757).
Also added a new hash for the draftjs-exporter package, as it was published in wheel form recently (see commit for more info).
=> Fix safety failures

Makefile, docker/DevDjangoDockerfile, docker/DevNodeDockerfile, docker/ProdDjangoDockerfile, package-lock.json, prod-docker-compose.yaml
Over in Kubernetes we want to specify the container user as a UID for security-hardening reasons. Right now, this is done by copying the UID set in the app's Dockerfile to the manifest.
Infra should actually own setting what that is in production, so let's *not* default the UID, and fail the build if it isn't passed. This means we can DRY up the situation here where we have a default arg in the Dockerfiles but also pass it through `docker-compose` from `make`. The situation with `docker-compose` is actually very similar, because it *has* to pass in the UID from the environment so that volume sharing will work. There isn't a default that will work for all dev workstation setups. So, have that be the one place it gets set.
Over in infra land we do still set the production UID in two places, …
=> No default UID, because dev env and CI both must supply it

package-lock.json
From npm audit:
```                                                                                                                                                       
LOW: 1523 - Prototype Pollution                                                                                                                               
Versions of `lodash` prior to 4.17.19 are vulnerable to Prototype Pollution.  The function `zipObjectDeep` allows a malicious user to modify the prototype of 
`Object` if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.         
This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code …
```
=> Update lodash for security advisory 1523

securethenews/dev-requirements.in
I was attempting to test out upgrading some dependencies in my dev env, and ran into a problem: Because `dev-requirements.in` includes `requirements.txt` via `-r`, it pulls in whatever versions and hashes were pinned by the last update of *production* dependencies. If we want to update something, this will cause conflicts.
I *think* that including `requirements.in` instead will attempt to resolve all the same dependencies as were resolved for prod, but be more flexible in allowing one of them to be upgraded by an upgraded package depending on it. Does this seem reasonable?
=> Include requirements.in not requirements.txt

securethenews/settings/base.py
Once I was finally able to get CI running with #255, I found an actual lint! I think we meant a raw string here since this is a regex.
=> flake8: \. is not a valid escape

.circleci/config.yml
The Python 3.5 container is on 3.5.9; let's match it. To do so we need to upgrade to the latest 16.04 image.
=> Update CircleCI python

scripts/version-file.sh
Improve how we use `git describe`, and also get the branch or tag name (`rev-parse` will return "`HEAD`" if a tag rather than a branch is checked out, which isn't very useful... I suppose this part can be reverted later).
Support for a future `production` branch is provisional for now, but this is how it might look.
=> Better git-describe output, will support future 'production' branch
